// // For this project development
// import '@vue/runtime-core';

// declare module '@vue/runtime-core' {
//   // GlobalComponents for Volar
//   // 注册组件
//   export interface GlobalComponents {
//     IvueAffix: typeof import('../src/index')['IvueAffix']
//     IvueAutoComplete: typeof import('../src/index')['IvueAutoComplete']
//     IvueAvatar: typeof import('../src/index')['IvueAvatar']
//     IvueBackTop: typeof import('../src/index')['IvueBackTop']
//     IvueBadge: typeof import('../src/index')['IvueBadge']
//     IvueBottomNav: typeof import('../src/index')['IvueBottomNav']
//     IvueBottomNavItem: typeof import('../src/index')['IvueBottomNavItem']
//     IvueBreadcrumb: typeof import('../src/index')['IvueBreadcrumb']
//     IvueBreadcrumbItem: typeof import('../src/index')['IvueBreadcrumbItem']
//     IvueButton: typeof import('../src/index')['IvueButton']
//     IvueCard: typeof import('../src/index')['IvueCard']
//     IvueCarousel: typeof import('../src/index')['IvueCarousel']
//     IvueCarouselItem: typeof import('../src/index')['IvueCarouselItem']
//     IvueCarouselLoop: typeof import('../src/index')['IvueCarouselLoop']
//     IvueCascader: typeof import('../src/index')['IvueCascader']
//     IvueCheckbox: typeof import('../src/index')['IvueCheckbox']
//     IvueCheckboxGroup: typeof import('../src/index')['IvueCheckboxGroup']
//     IvueChip: typeof import('../src/index')['IvueChip']
//     IvueCircular: typeof import('../src/index')['IvueCircular']
//     IvueCollapse: typeof import('../src/index')['IvueCollapse']
//     IvueCollapsePanel: typeof import('../src/index')['IvueCollapsePanel']
//     IvueCountDown: typeof import('../src/index')['IvueCountDown']
//     IvueCountUp: typeof import('../src/index')['IvueCountUp']
//     IvueDatePicker: typeof import('../src/index')['IvueDatePicker']
//     IvueEllipsis: typeof import('../src/index')['IvueEllipsis']
//     IvueForm: typeof import('../src/index')['IvueForm']
//     IvueFormItem: typeof import('../src/index')['IvueFormItem']
//     IvueIcon: typeof import('../src/index')['IvueIcon']
//     IvueImage: typeof import('../src/index')['IvueImage']
//     IvueImagePreview: typeof import('../src/index')['IvueImagePreview']
//     IvueInput: typeof import('../src/index')['IvueInput']
//     IvueInputNumber: typeof import('../src/index')['IvueInputNumber']
//     IvueLoadingBar: typeof import('../src/index')['IvueLoadingBar']
//     IvueMenu: typeof import('../src/index')['IvueMenu']
//     IvueMenuItem: typeof import('../src/index')['IvueMenuItem']
//     IvueSubmenu: typeof import('../src/index')['IvueSubmenu']
//     IvueMenuGroup: typeof import('../src/index')['IvueMenuGroup']
//     IvueMessage: typeof import('../src/index')['IvueMessage']
//     IvueModal: typeof import('../src/index')['IvueModal']
//     IvueNotice: typeof import('../src/index')['IvueNotice']
//     IvueNoticeBar: typeof import('../src/index')['IvueNoticeBar']
//     IvuePage: typeof import('../src/index')['IvuePage']
//     IvuePopover: typeof import('../src/index')['IvuePopover']
//     IvueProgress: typeof import('../src/index')['IvueProgress']
//     IvueRadio: typeof import('../src/index')['IvueRadio']
//     IvueRadioGroup: typeof import('../src/index')['IvueRadioGroup']
//     IvueRelativeTime: typeof import('../src/index')['IvueRelativeTime']
//     IvueScrollbar: typeof import('../src/index')['IvueScrollbar']
//     IvueSelect: typeof import('../src/index')['IvueSelect']
//     IvueOption: typeof import('../src/index')['IvueOption']
//     IvueOptionGroup: typeof import('../src/index')['IvueOptionGroup']
//     IvueSkeleton: typeof import('../src/index')['IvueSkeleton']
//     IvueSkeletonItem: typeof import('../src/index')['IvueSkeletonItem']
//     IvueSpin: typeof import('../src/index')['IvueSpin']
//     IvueSteps: typeof import('../src/index')['IvueSteps']
//     IvueStep: typeof import('../src/index')['IvueStep']
//     IvueSwitch: typeof import('../src/index')['IvueSwitch']
//     IvueTable: typeof import('../src/index')['IvueTable']
//     IvueTableColumn: typeof import('../src/index')['IvueTableColumn']
//     IvueTabs: typeof import('../src/index')['IvueTabs']
//     IvueTab: typeof import('../src/index')['IvueTab']
//     IvueTabItem: typeof import('../src/index')['IvueTabItem']
//     IvueTooltip: typeof import('../src/index')['IvueTooltip']
//   }

//   interface ComponentCustomProperties {
//     $IvueImagePreview: typeof import('../src/index')['IvueImagePreview']
//     $message: typeof import('../src/index')['IvueMessage']
//     $IvueModal: typeof import('../src/index')['IvueModal']
//     $notice: typeof import('../src/index')['IvueNotice']
//     $IvueSpin: typeof import('../src/index')['IvueSpin']
//   }
// }

// export {};
